<?php

namespace Phossa\Di\Definition\Loader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-20 at 19:20:12.
 */
class LoaderJsonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var LoaderJson
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * test not found
     *
     * @covers Phossa\Di\Definition\Loader\LoaderJson::loadFromFile
     * @expectedException Phossa\Di\Exception\LogicException
     * @expectedExceptionCode Phossa\Di\Message\Message::DEFINITION_NOT_FOUND
     */
    public function testLoadFromFile1()
    {
        $this->assertEquals(
            ['cache' => ['bingo']], @LoaderJson::loadFromFile(__DIR__ . '/def2.php')
        );
    }

    /**
     * normal case
     *
     * @covers Phossa\Di\Definition\Loader\LoaderJson::loadFromFile
     */
    public function testLoadFromFile2()
    {
        $this->assertEquals(
            ['cache' => ['bingo']], LoaderJson::loadFromFile(__DIR__ . '/def2.json')
        );
    }

    /**
     * format error
     *
     * @covers Phossa\Di\Definition\Loader\LoaderJson::loadFromFile
     * @expectedException Phossa\Di\Exception\LogicException
     * @expectedExceptionCode Phossa\Di\Message\Message::DEFINITION_FORMAT_ERR
     */
    public function testLoadFromFile3()
    {
        $this->assertEquals(
            ['cache' => ['bingo']], LoaderJson::loadFromFile(__DIR__ . '/def3.json')
        );
    }

}
