<?php

namespace Phossa\Di\Definition\Loader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-20 at 19:20:13.
 */
class LoaderXmlTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var LoaderXml
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Phossa\Di\Definition\Loader\LoaderXml::loadFromFile
     */
    public function testLoadFromFile1()
    {
        $this->assertEquals(
            ['cache' => 'bingo'], LoaderXml::loadFromFile(__DIR__ . '/def4.xml')
        );
    }

    /**
     * format error
     *
     * @covers Phossa\Di\Definition\Loader\LoaderXml::loadFromFile
     * @expectedException Phossa\Di\Exception\LogicException
     * @expectedExceptionCode Phossa\Di\Message\Message::DEFINITION_FORMAT_ERR
     */
    public function testLoadFromFile2()
    {
        $this->assertEquals(
            ['cache' => 'bingo'], LoaderXml::loadFromFile(__DIR__ . '/def5.xml')
        );
    }

    /**
     * file not found
     *
     * @covers Phossa\Di\Definition\Loader\LoaderXml::loadFromFile
     * @expectedException Phossa\Di\Exception\LogicException
     * @expectedExceptionCode Phossa\Di\Message\Message::DEFINITION_FORMAT_ERR
     */
    public function testLoadFromFile3()
    {
        $this->assertEquals(
            ['cache' => 'bingo'], LoaderXml::loadFromFile(__DIR__ . '/def6.xml')
        );
    }

}
