<?php

namespace Phossa\Di\Message;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-20 at 19:20:11.
 */
class MessageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Message
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Phossa\Di\Message\Message::get
     */
    public function testGet()
    {
        $this->assertEquals(
            'Service "one" method "two" error', Message::get(
                Message::SERVICE_METHOD_ERROR, 'one', 'two'
            )
        );
    }

}
