<?php

namespace Phossa\Di\Extension;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-20 at 19:20:14.
 */
class ExtensionAbstractTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ExtensionAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        include_once __DIR__ . '/NewExtension1.php';
        include_once __DIR__ . '/NewExtension2.php';
        include_once __DIR__ . '/NewExtension3.php';
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Phossa\Di\Extension\ExtensionAbstract::getName
     * @expectedException Phossa\Di\Exception\LogicException
     * @expectedExceptionCode Phossa\Di\Message\Message::EXTENION_INVALID_NAME
     */
    public function testGetName1()
    {
        (new NewExtension1())->getName();
    }

    /**
     * @covers Phossa\Di\Extension\ExtensionAbstract::getName
     * @expectedException Phossa\Di\Exception\LogicException
     * @expectedExceptionCode Phossa\Di\Message\Message::EXTENION_INVALID_CLASS
     */
    public function testGetName2()
    {
        (new NewExtension2())->getName();
    }

    /**
     * @covers Phossa\Di\Extension\ExtensionAbstract::getName
     */
    public function testGetName3()
    {
        $this->assertEquals('newextension3', (new NewExtension3())->getName());
    }

}
